from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

BASE_DIR = Path(__file__).resolve().parents[1]
OUTPUT_DIR = BASE_DIR / "public" / "pdf"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

TITLE_STYLE = ParagraphStyle(
    name="Title",
    fontSize=18,
    leading=22,
    spaceAfter=12,
    textColor=colors.HexColor("#0f172a"),
    fontName="Helvetica-Bold",
)

SUBTITLE_STYLE = ParagraphStyle(
    name="Subtitle",
    fontSize=11,
    leading=14,
    textColor=colors.HexColor("#475569"),
    spaceAfter=8,
)

BODY_STYLE = ParagraphStyle(
    name="Body",
    fontSize=10,
    leading=14,
    textColor=colors.HexColor("#1e293b"),
)

FOOTER_STYLE = ParagraphStyle(
    name="Footer",
    fontSize=8,
    leading=12,
    textColor=colors.HexColor("#475569"),
    alignment=1,
)


class ReceiptRenderer:
    def __init__(self, payload: Dict[str, Any]):
        self.payload = payload
        self.file_name = payload.get("fileName", "tipsplit-breakdown.pdf")
        self.path = OUTPUT_DIR / self.file_name

    def build_story(self):
        story: List[Any] = []
        story.append(Paragraph("TipSplit breakdown", TITLE_STYLE))
        story.append(
            Paragraph(
                "Session snapshot generated from tipsplit.app. Share this file with finance, ops, or whoever checks the math.",
                SUBTITLE_STYLE,
            )
        )

        story.append(Paragraph("Session summary", BODY_STYLE))
        summary_data = [
            ["Bill amount", self.payload.get("bill", "-")],
            ["Sales tax %", f"{self.payload.get('taxPercent', '-') }%"],
            ["Service fee %", f"{self.payload.get('servicePercent', '-') }%"],
            [
                "Tip %",
                f"{self.payload.get('tipPercent', '-') }% ({self.payload.get('tipBasisLabel', 'pre-tax')})",
            ],
            ["Split between", f"{self.payload.get('peopleCount', '-') } people"],
        ]
        story.append(self._make_table(summary_data))
        story.append(Spacer(1, 0.2 * inch))

        story.append(Paragraph("Line items", BODY_STYLE))
        breakdown_rows = self.payload.get("breakdown", [])
        breakdown_data = [["Label", "Amount"]]
        for row in breakdown_rows:
            breakdown_data.append([row.get("label", "-"), row.get("valueFormatted", "")])
        story.append(self._make_table(breakdown_data, header=True))
        story.append(Spacer(1, 0.2 * inch))

        story.append(Paragraph("Per person focus", BODY_STYLE))
        per_person_table = [
            ["Metric", "Value"],
            ["Per person total", self.payload.get("perPersonFormatted", "-")],
            ["Tip per person", self.payload.get("tipPerPersonFormatted", "-")],
            ["Kitchen share reserve", self.payload.get("kitchenReserveFormatted", "-")],
        ]
        story.append(self._make_table(per_person_table, header=True))
        story.append(Spacer(1, 0.2 * inch))

        story.append(Paragraph("Insights", BODY_STYLE))
        insights = self.payload.get("insights", [])
        if insights:
            insights_table = [["Label", "Value", "Notes"]]
            for insight in insights:
                insights_table.append(
                    [
                        insight.get("label", "-"),
                        insight.get("value", "-"),
                        insight.get("caption", ""),
                    ]
                )
            story.append(self._make_table(insights_table, header=True))
        else:
            story.append(Paragraph("No insights supplied.", BODY_STYLE))

        story.append(Spacer(1, 0.3 * inch))
        story.append(
            Paragraph(
                "Generated by TipSplit — hospitality-ready bill intelligence.",
                FOOTER_STYLE,
            )
        )
        return story

    def _make_table(self, data: List[List[str]], header: bool = False):
        table = Table(data, hAlign="LEFT")
        style_commands = [
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#0f172a")),
            ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
        ]
        if header:
            style_commands.extend(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ]
            )
        table.setStyle(TableStyle(style_commands))
        return table

    def render(self):
        doc = SimpleDocTemplate(
            str(self.path),
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=48,
            bottomMargin=48,
        )
        doc.build(self.build_story())
        return self.path


def render_from_json(payload_json: str):
    try:
        payload = json.loads(payload_json)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON payload: {exc}")
    renderer = ReceiptRenderer(payload)
    output_path = renderer.render()
    print(output_path)


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        raise SystemExit("Usage: python render_pdf.py '<json payload>'")
    render_from_json(sys.argv[1])
